### PR TITLE
chore(eslint): added eslint and remove tslint

### PR DESCRIPTION
**Pull request by Tony133**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?
N/A

## Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

## Other information
This PR, added eslint and remove tslint, merge after this pull #300

### CODE REVIEW

**Comment by Tony133** [comment]
Complex conflicts should be resolved, but unfortunately I don't have the permissions to resolve them, some idea?

**Comment by Tony133** [comment]
@kamilmysliwiec as soon as you find some time can you look at this pull if it goes well? I tried to resolve complex conflicts that should be resolved, but unfortunately I don't have the permissions to resolve them, any ideas?

**Comment by Tony133** [comment]
@kamilmysliwiec do you know how I can solve the complex permissions for this pull?

**Comment by kamilmysliwiec** [comment]
@Tony133 thanks for your contribution, but please, for your future reference - you don't have to mention me multiple times in the same issue/PR. I have seen this PR but I have other, more important work ATM. Will get back to this as soon as I have slightly more time.

**Comment by Tony133** [comment]
Ok I wanted to know if it's my problem, Can I write to you on discord if I have any doubts?

so I'm not writing you here.

Answer me as soon as you have time no problem.

Sorry again   🙏

**Pull request closed without merging**
